services:
  mee7:
    container_name: mee7
    restart: unless-stopped
    image: ghcr.io/cubeur-manchot/mee7:latest
    env_file: .env
    environment:
      - PREFIX=!
      - PBLIST_EVENTS=3x3,4x4,5x5,3BLD,OH,Megaminx,Clock,Pyraminx
