services:
  mee7:
    container_name: mee7
    restart: unless-stopped
    image: ghcr.io/cubeur-manchot/mee7:latest
    environment:
      - TOKEN=${TOKEN}
      - GUILD_ID=329175643877015553
      - ALGOFTHEDAY_FILE_ID=1RUYN-sqngHdW_SEVG3_BfUoj_M2kKaam
      - BESTCUBES_EVENTS=3x3,2x2,4x4,5x5,6x6,7x7,Megaminx,Pyraminx,Skewb,Square one,Clock,FTO,Non-WCA
      - BESTCUBES_SPREADSHEET_ID=1UzGN5xEl-noA3JsEFC6HJL1TL9x7TuKGiDYa64WEd88
      - PBLIST_EVENTS=3x3,4x4,5x5,OH,3BLD,Megaminx,Pyraminx,Clock,FTO
      - PBLIST_SPREADSHEET_ID=14RKLrMwBD3VPjZfXhTy4hiMnq3_skEV8Jus7lctjtN0
      - STRINGSELECT_SUFFIX=StringSelectCustomId
