services:
  mee7:
    container_name: mee7-dev
    build: .
    stop_grace_period: 3s
    volumes:
      - ./secrets/googleApi_serviceAccountKey.json:/run/secrets/googleApi_serviceAccountKey.json:ro
    env_file: .env
    environment:
      - GUILD_ID=422718228913979392
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/googleApi_serviceAccountKey.json
